project:
  type: website
  output-dir: docs

toc: true
toc-depth: 3

format:
  html:
    theme: cerulean
    css: styles.css
    html-math-method: katex
    code-fold: false
    code-link: true
    code-copy: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"

execute:
  cache: true

website:
  title: "mizer course"
  site-url: "https://course.mizer.sizespectrum.org"
  favicon: images/favicon-16x16.png
  repo-url: https://github.com/sizespectrum/mizerCourse
  repo-actions: [edit, issue]
  twitter-card:
    site: "@mizer_model"
    creator: "gustavdelius"
  opengraph: true
  search: 
    location: navbar
    type: textbox
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Prepare"
        contents:
          - text: Introduce yourself
            href: prepare/introductions.qmd
          - text: Install tools
            href: prepare/install.qmd
          - text: Use Git and GitHub
            href: prepare/use-git-and-github.qmd
          - text: Watch introduction
            href: prepare/introduction-to-mizer.qmd
      - section: "Week 1: Understand"
        href: understand/index.qmd
        contents: 
          - text: Plot size spectra
            href: understand/plotting-spectra.qmd
          - text: Shapes of spectra
            href: understand/shapes.qmd
          - text: Predation
            href: understand/predation.qmd
          - text: Dynamics of spectra
            href: understand/dynamics.qmd
          - text: Species interactions
            href: understand/interactions.qmd
      - section: "Week 2: Build"
        href: index.qmd
        contents:
          - text: Create first model
            href: build/build-model.qmd
          - text: Set multiple resources
            href: build/multiple-resources.qmd
          - text: Tune model
            href: build/tune-model.qmd
          - text: Find species parameters
            href: build/species-parameters.qmd
          - text: Build your own model
            href: build/build-your-own.qmd
      - section: "Week 3: Use"
        href: index.qmd
        contents:
          - text: Simulate change
            href: use/simulate.qmd
          - text: Refine model
            href: use/refine.qmd
          - text: Tune sensitivity
            href: use/tune-sensitivity.qmd
          - text: Change resources
            href: use/change-resources.qmd
          - text: Run your own scenarios
            href: use/run-your-own.qmd


comments:
  giscus: 
    repo: sizespectrum/mizerCourse
    category: Comments
    reactions-enabled: false
    input-position: bottom
    repo-id: R_kgDOHlJwYg
    category-id: DIC_kwDOHlJwYs4CP_7j
    data-loading: lazy
    